### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by perfectEmpathy** [liambaloh/DMI2PNG#1]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\dmi2png\GifCreator\GifCreator.php on line 133

This is what I get when trying to go "https://github.com/liambaloh/DMI2PNG"

**Comment by liambaloh** [comment]
Hello! Thanks for letting me know - this is now fixed and should work for at least PHP 7.4. I haven't tested on other recent versions of PHP but it's likely to work on them too.

**Comment by perfectEmpathy** [comment]
Whoah. You're fast.

But this is not over, dude. Look.

_cavefloor.dmi

Fatal error: Uncaught Error: Call to undefined function imagecreatefrompng() in C:\xampp\htdocs\dmi2png\index.php:548 Stack trace: #0 {main} thrown in C:\xampp\htdocs\dmi2png\index.php on line 548_

This is what I get when trying to refresh.

**Comment by liambaloh** [comment]
Looks like the function is part of the GD package. In XAMPP the GD package is installed by default, though you may need to install it separately, depending on your php configuration.

![image](https://user-images.githubusercontent.com/1364475/134953270-966c1674-8ce0-4895-bb2a-27cae7293ec3.png)

![image](https://user-images.githubusercontent.com/1364475/134953779-73cce1c2-79d6-438d-bdaf-81d809caaf9d.png)

**Comment by liambaloh** [comment]
Did this solve it for you? If not let me know and we can look into it further

**Comment by perfectEmpathy** [comment]
Nah. Same problem, different PC.

things.dmi
*Fatal error*: Uncaught Error: Call to undefined function
imagecreatefrompng() in C:\xampp\htdocs\dmi2png\index.php:548 Stack trace:
#0 {main} thrown in *C:\xampp\htdocs\dmi2png\index.php* on line *548*

пн, 4 окт. 2021 г. в 00:29, Liam Baloh ***@***.***>:

**Comment by perfectEmpathy** [comment]
Forget it! This helped.

https://stackoverflow.com/questions/7851011/how-do-i-install-gd-on-my-windows-server-version-of-php

вт, 28 дек. 2021 г. в 03:49, Иван Кутузов ***@***.***>:
