### ISSUE TITLE
undefined function imagecreatefrompngs

### ISSUE THREAD

**Issue by lfricken** [liambaloh/DMI2PNG#2]
Fatal error: Uncaught Error: Call to undefined function imagecreatefrompngs() in C:\xampp\htdocs\dmi2png\index.php:548 Stack trace: #0 {main} thrown in C:\xampp\htdocs\dmi2png\index.php on line 548

I have php_gd.dll in my C:/xampp/php/ext/ folder.
I tried setting in my php.ini file:
extension=php_gd
extension=C:/xampp/php/ext/php_gd.dll
extension_dir="C:/xampp/php/ext"

Tried launching as admin. Still the same.

**Comment by liambaloh** [comment]
Hello! `imagecreatefrompngs(..)` is not a function used in this project, the function in index.php:548 is `imagecreatefrompng(..)` - notice the lack of an "s" at the end: https://github.com/liambaloh/DMI2PNG/blob/master/index.php#L548

![image](https://user-images.githubusercontent.com/1364475/135771396-cf698aca-6717-45c6-bc04-bf14f582165b.png)

`imagecreatefrompng(..)` is a part of the GD library, while `imagecreatefrompngs(..)` indeed doesn't exist. Please change the call in your source to `imagecreatefrompng(..)`. If that alone doesn't fix it, please revert any other changes applied to the local version. Even if you checked out your fork of this repository, index.php:546 in your fork also correctly calls `imagecreatefrompng(..)` and not `imagecreatefrompngs(..)`: https://github.com/lfricken/DMI2PNG/blob/master/index.php#L546, though that fork is 3 recent commits out of date so may need an update.

**Comment by liambaloh** [comment]
Hello! Did that solve the issue you were having?
