### ISSUE TITLE
 Call to undefined function imagecreatefrompng() in C:\xampp\htdocs\dmi2png\DMI2PNG-master\index.php:548 Stack trace: #0 {main} thrown in C:\xampp\htdocs\dmi2png\DMI2PNG-master\index.php on line 548

### ISSUE THREAD

**Issue by garrett77** [liambaloh/DMI2PNG#3]
Fatal error: Uncaught Error: Call to undefined function imagecreatefrompng() in C:\xampp\htdocs\dmi2png\DMI2PNG-master\index.php:548 Stack trace: #0 {main} thrown in C:\xampp\htdocs\dmi2png\DMI2PNG-master\index.php on line 548

I get this error when follow the instructions verbatim. I am almost completely clueless on how this stuff works so I'm probably just doing something wrong here. If anyone can help that'd be appreciated.
If you can't tell, I'm using Windows. (10, if that matters.)
I am probably missing some dependency.
I apologize if this is unhelpful or if I'm doing this wrong, again.

**Comment by liambaloh** [comment]
Hello! Yes, you need to enable the GD library in php (I believe this is done in an ini file accessible through xampp). I'm not currently able to test and work out a process that'll work for sure. 

Hopefully that gives you enough information to find a guide online. I found https://phpandmysql.com/extras/enable-gd-for-xampp/ but can't verify it actually works. Also according to https://write.corbpie.com/how-to-enable-gd-library-with-xampp-php-8-on-windows/ the ini name changed so try using "gd" or "gd2" in there and see which works.

Let me know if this solves it or if you need more help. I'll be able to look at it closer in a few days but hopefully you can get it sorted by then.

**Comment by 77seven77seven** [comment]
> Hello! Yes, you need to enable the GD library in php (I believe this is done in an ini file accessible through xampp). I'm not currently able to test and work out a process that'll work for sure.
> 
> Hopefully that gives you enough information to find a guide online. I found https://phpandmysql.com/extras/enable-gd-for-xampp/ but can't verify it actually works. Also according to https://write.corbpie.com/how-to-enable-gd-library-with-xampp-php-8-on-windows/ the ini name changed so try using "gd" or "gd2" in there and see which works.
> 
> Let me know if this solves it or if you need more help. I'll be able to look at it closer in a few days but hopefully you can get it sorted by then.

ah thanks mate

**Comment by garrett77** [comment]
I found another way to do what I needed (outside of this program), sorry. But I hope this helped someone else.
